/**
 * Dream symbol corpus — independent motif entries with layered hints.
 * Meanings are probabilistic motifs, never fate claims.
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   aliases: string[],
 *   themes: string[],
 *   psychological: string,
 *   classical: string,
 *   jungHint: string|null,
 * }} DreamSymbol
 */

/** @type {DreamSymbol[]} */
export const DREAM_SYMBOL_CORPUS = Object.freeze([
  {
    id: 'water',
    name: 'su',
    aliases: ['su', 'sular', 'dere', 'nehir', 'ırmak', 'ırmak'],
    themes: ['duygu', 'akış', 'arınma'],
    psychological: 'Duygusal akış, bastırılmış hislerin yüzeye çıkması veya arınma ihtiyacı.',
    classical: 'Klasik yorumlarda berrak su çoğu zaman huzur/arınma; bulanık su kaygı veya belirsizlikle ilişkilendirilir — kesin hüküm değildir.',
    jungHint: null,
  },
  {
    id: 'sea',
    name: 'deniz',
    aliases: ['deniz', 'okyanus', 'dalga', 'dalgalar', 'sahil'],
    themes: ['bilinçaltı', 'derinlik', 'genişlik'],
    psychological: 'Bilinçaltının genişliği; kontrol edilemeyen duygusal derinlik.',
    classical: 'Deniz bazen geniş nimet veya büyük imtihan motifi olarak okunur; bağlam şarttır.',
    jungHint: 'Great Mother',
  },
  {
    id: 'snake',
    name: 'yılan',
    aliases: ['yılan', 'yılanlar', 'ejderha'],
    themes: ['dönüşüm', 'korku', 'gizli güç'],
    psychological: 'Bastırılmış enerji, dönüşüm korkusu veya iyileşme potansiyeli.',
    classical: 'Klasik kaynaklarda yılan düşmana, şifaya veya gizli güce işaret edebilir — tek anlam yoktur.',
    jungHint: 'Shadow',
  },
  {
    id: 'house',
    name: 'ev',
    aliases: ['ev', 'evim', 'evde', 'konut', 'apartman', 'oda'],
    themes: ['benlik', 'güvenlik', 'iç dünya'],
    psychological: 'Psikede “benlik evi”; odalar farklı benlik katmanlarını gösterebilir.',
    classical: 'Ev bazen kişinin hali, ailesi veya iç düzeniyle ilişkilendirilir.',
    jungHint: null,
  },
  {
    id: 'door',
    name: 'kapı',
    aliases: ['kapı', 'kapılar', 'eşik', 'giriş', 'çıkış'],
    themes: ['geçiş', 'seçim', 'eşik'],
    psychological: 'Bir eşik: açmak veya kapatmak — geçiş veya sınır koyma.',
    classical: 'Kapı bazen fırsat, bazen engel olarak yorumlanır; yön ve duygu kritiktir.',
    jungHint: null,
  },
  {
    id: 'key',
    name: 'anahtar',
    aliases: ['anahtar', 'anahtarlar', 'kilit'],
    themes: ['çözüm', 'erişim', 'giz'],
    psychological: 'Çözüme erişim; kilitli kalmış bir konuya anahtar aramak.',
    classical: 'Anahtar bazen sır, yetki veya çözüm motifi olarak okunur.',
    jungHint: null,
  },
  {
    id: 'bird',
    name: 'kuş',
    aliases: ['kuş', 'kuşlar', 'kanat', 'uçmak', 'uçuyorum'],
    themes: ['özgürlük', 'ruh', 'mesaj'],
    psychological: 'Özgürleşme arzusu veya bakış açısını yükseltme ihtiyacı.',
    classical: 'Kuş bazen müjde, ruh hali veya haber motifi olarak geçer.',
    jungHint: null,
  },
  {
    id: 'baby',
    name: 'bebek',
    aliases: ['bebek', 'yenidoğan', 'kundak'],
    themes: ['başlangıç', 'kırılganlık', 'yeni benlik'],
    psychological: 'Yeni bir yön, kırılgan bir potansiyel veya bakım ihtiyacı.',
    classical: 'Bebek bazen yeni bir iş, umut veya sorumlulukla ilişkilendirilir.',
    jungHint: 'Child',
  },
  {
    id: 'child',
    name: 'çocuk',
    aliases: ['çocuk', 'çocuklar', 'çocuğum', 'küçük çocuk'],
    themes: ['masumiyet', 'oyun', 'iç çocuk'],
    psychological: 'İç çocuk; unutulmuş merak, kırılganlık veya oyun hali.',
    classical: 'Çocuk bazen sevinç, bazen kaygı yükü olarak okunabilir.',
    jungHint: 'Child',
  },
  {
    id: 'dog',
    name: 'köpek',
    aliases: ['köpek', 'köpekler', 'it'],
    themes: ['sadakat', 'koruma', 'içgüdü'],
    psychological: 'Sadakat, güven veya ihanet korkusu; içgüdüsel bağ.',
    classical: 'Köpek bazen sadık dost, bazen düşman motifi taşır — davranışa bakılır.',
    jungHint: null,
  },
  {
    id: 'cat',
    name: 'kedi',
    aliases: ['kedi', 'kediler'],
    themes: ['bağımsızlık', 'sezgi', 'gizlilik'],
    psychological: 'Bağımsızlık ihtiyacı, sezgisel sınır veya gizli duygular.',
    classical: 'Kedi klasik yorumlarda hem bereket hem de temkin motifi olabilir.',
    jungHint: 'Anima',
  },
  {
    id: 'tree',
    name: 'ağaç',
    aliases: ['ağaç', 'ağaçlar', 'orman', 'dal'],
    themes: ['kök', 'büyüme', 'yaşam'],
    psychological: 'Kökleşme, büyüme veya aile/soy bağları.',
    classical: 'Ağaç bazen ömür, bereket veya sabitlik olarak okunur.',
    jungHint: null,
  },
  {
    id: 'fire',
    name: 'ateş',
    aliases: ['ateş', 'alev', 'yangın', 'yanıyor', 'yanmak'],
    themes: ['tutku', 'öfke', 'dönüşüm'],
    psychological: 'Yoğun duygu — öfke, tutku veya arınma ateşi.',
    classical: 'Ateş bazen fitne, bazen arınma/bereket olarak yorumlanır; kontrol kritiktir.',
    jungHint: null,
  },
  {
    id: 'rain',
    name: 'yağmur',
    aliases: ['yağmur', 'yağmur yağıyor', 'sağanak'],
    themes: ['arınma', 'bereket', 'melankoli'],
    psychological: 'Duygusal boşalma, ferahlama veya hüznün yumuşaması.',
    classical: 'Yağmur klasik olarak çoğu zaman rahmet/bereket motifi taşır.',
    jungHint: null,
  },
  {
    id: 'stairs',
    name: 'merdiven',
    aliases: ['merdiven', 'basamak', 'merdivenler', 'çıkıyorum', 'iniyorum'],
    themes: ['yükseliş', 'iniş', 'aşama'],
    psychological: 'Bilinç düzeyinde yükselme veya inme; aşamalı değişim.',
    classical: 'Merdiven bazen makam, bazen zorluk merdiveni olarak okunur.',
    jungHint: 'Hero',
  },
  {
    id: 'sky',
    name: 'gökyüzü',
    aliases: ['gökyüzü', 'gök', 'sema', 'ufuk'],
    themes: ['genişlik', 'umut', 'sınır'],
    psychological: 'Zihinsel genişlik, umut veya kontrol edilemeyen alan.',
    classical: 'Gökyüzü bazen yüksek niyet veya kaderin genişliği motifi taşır — kesin değil.',
    jungHint: null,
  },
  {
    id: 'sun',
    name: 'güneş',
    aliases: ['güneş', 'güneşli'],
    themes: ['bilinç', 'netlik', 'canlılık'],
    psychological: 'Aydınlanma, enerji, görünür olmak.',
    classical: 'Güneş klasik olarak çoğu zaman hayır, şöhret veya ferahlıkla ilişkilendirilir.',
    jungHint: null,
  },
  {
    id: 'moon',
    name: 'ay',
    aliases: ['ay', 'dolunay', 'hilal'],
    themes: ['sezgi', 'döngü', 'gölge'],
    psychological: 'Sezgisel alan, döngüsel duygu, görünmeyen yan.',
    classical: 'Ay bazen değişim, bazen iç dünya hali olarak okunur.',
    jungHint: 'Anima',
  },
  {
    id: 'star',
    name: 'yıldız',
    aliases: ['yıldız', 'yıldızlar'],
    themes: ['umut', 'rehberlik', 'yön'],
    psychological: 'Uzak bir umut, rehber ışık veya yön arayışı.',
    classical: 'Yıldız bazen müjde veya yüksek niyet motifi olarak geçer.',
    jungHint: null,
  },
  {
    id: 'death',
    name: 'ölüm',
    aliases: ['ölüm', 'ölmek', 'öldü', 'cenaze', 'mezar', 'kabir'],
    themes: ['bitiş', 'dönüşüm', 'yas'],
    psychological: 'Bir dönemin bitişi, yas veya kimlik dönüşümü — fiziksel ölüm kehaneti değildir.',
    classical: 'Klasik yorumda ölüm bazen uzun ömür veya büyük değişim motifi olarak da okunur; tek anlam yoktur.',
    jungHint: 'Shadow',
  },
  {
    id: 'wedding',
    name: 'düğün',
    aliases: ['düğün', 'nikah', 'gelinlik', 'damat', 'gelin'],
    themes: ['birleşme', 'sözleşme', 'geçiş'],
    psychological: 'İçsel birleşme, taahhüt veya yeni bir bağlanma aşaması.',
    classical: 'Düğün bazen sevinç, bazen önemli bir bağ/sözleşme motifi taşır.',
    jungHint: 'Anima',
  },
  {
    id: 'car',
    name: 'araba',
    aliases: ['araba', 'otomobil', 'araç', 'direksiyon'],
    themes: ['yön', 'kontrol', 'hayat yolu'],
    psychological: 'Hayatın yönü ve kontrol hissi — kim sürüyor?',
    classical: 'Araç bazen dünya işleri, yolculuk veya statü motifi olarak okunur.',
    jungHint: null,
  },
  {
    id: 'train',
    name: 'tren',
    aliases: ['tren', 'vagon', 'ray'],
    themes: ['kaçırılan fırsat', 'rota', 'zaman'],
    psychological: 'Belirlenmiş bir rota; yetişme kaygısı veya kolektif akış.',
    classical: 'Tren bazen yolculuk veya kaçırılan vakit motifi taşır.',
    jungHint: null,
  },
  {
    id: 'plane',
    name: 'uçak',
    aliases: ['uçak', 'uçakta', 'havalimanı'],
    themes: ['yükseliş', 'uzaklık', 'geçiş'],
    psychological: 'Büyük bir geçiş, bakış açısını yükseltme veya mesafe.',
    classical: 'Uçak modern semboldür; klasik çerçevede “yükseliş/yolculuk” motifiyle okunabilir.',
    jungHint: 'Hero',
  },
  {
    id: 'money',
    name: 'para',
    aliases: ['para', 'paralar', 'nakit', 'banknot'],
    themes: ['değer', 'güvenlik', 'enerji'],
    psychological: 'Değer görme, güvenlik kaygısı veya enerji alışverişi.',
    classical: 'Para bazen rızık, bazen dünya meşgalesi olarak yorumlanır.',
    jungHint: null,
  },
  {
    id: 'gold',
    name: 'altın',
    aliases: ['altın', 'altınlar', 'ziynet'],
    themes: ['değer', 'öz', 'arınmış'],
    psychological: 'İçsel değer, olgunlaşmış bir öz veya “kıymetli olan”.',
    classical: 'Altın klasik olarak çoğu zaman hayır, değer veya sınav motifi taşır.',
    jungHint: null,
  },
  {
    id: 'white',
    name: 'beyaz',
    aliases: ['beyaz', 'beyazlar'],
    themes: ['saflık', 'başlangıç', 'berraklık'],
    psychological: 'Saflık arzusu, temiz sayfa veya berraklık ihtiyacı.',
    classical: 'Beyaz çoğu klasik okumada hayır ve temizlikle ilişkilendirilir.',
    jungHint: null,
  },
  {
    id: 'black',
    name: 'siyah',
    aliases: ['siyah', 'kara'],
    themes: ['bilinmeyen', 'yas', 'giz'],
    psychological: 'Bilinmeyen alan, yas veya henüz bilinçleşmemiş içerik.',
    classical: 'Siyah bazen belirsizlik veya ağırlık motifi taşır; tek başına hüküm değildir.',
    jungHint: 'Shadow',
  },
  {
    id: 'mirror',
    name: 'ayna',
    aliases: ['ayna', 'aynalar'],
    themes: ['öz-yansıma', 'kimlik', 'yüzleşme'],
    psychological: 'Kendine bakmak; kimlik yüzleşmesi veya parçalı benlik.',
    classical: 'Ayna bazen iç yüz, bazen aldatıcı görünüm motifi olarak okunur.',
    jungHint: 'Shadow',
  },
  {
    id: 'bridge',
    name: 'köprü',
    aliases: ['köprü', 'köprüler'],
    themes: ['geçiş', 'bağ', 'risk'],
    psychological: 'İki durum arasında geçiş; bağ kurma veya risk alma.',
    classical: 'Köprü geçiş ve aracılık motifi taşır.',
    jungHint: 'Hero',
  },
  {
    id: 'teeth',
    name: 'diş',
    aliases: ['diş', 'dişler', 'dişim'],
    themes: ['kaygı', 'kontrol', 'görünüm'],
    psychological: 'Kontrol kaybı kaygısı, güçsüzlük hissi veya iletişim stresi.',
    classical: 'Diş düşmesi klasik yorumlarda sıkça yakınlarla ilgili kaygı motifi taşır — kesin değildir.',
    jungHint: null,
  },
  {
    id: 'falling',
    name: 'düşmek',
    aliases: ['düşmek', 'düşüyorum', 'düştüm', 'uçurum'],
    themes: ['kontrol kaybı', 'güvensizlik', 'bırakış'],
    psychological: 'Kontrol kaybı korkusu veya bırakmaya direnç.',
    classical: 'Düşmek bazen makam kaybı veya uyanış motifi olarak okunur.',
    jungHint: null,
  },
  {
    id: 'chase',
    name: 'kovalanma',
    aliases: ['kovalan', 'kovalıyor', 'kaçıyorum', 'kaçıyordum', 'kaçıyor', 'takip'],
    themes: ['kaçış', 'baskı', 'yüzleşme'],
    psychological: 'Yüzleşilmeyen bir durumdan kaçış; baskı veya kaygı.',
    classical: 'Kovalanma çoğu zaman sıkıntıdan kaçış motifi taşır.',
    jungHint: 'Shadow',
  },
  {
    id: 'devil',
    name: 'şeytan',
    aliases: ['şeytan', 'iblis', 'karanlık figür', 'kötü ruh'],
    themes: ['ayartma', 'sınav', 'karanlık güç'],
    psychological: 'Bastırılmış korku veya içsel ayartmanın dışsallaşmış hali; yüzleşme ve sınır koyma çağrısı olabilir.',
    classical: 'Klasik yorumlarda şeytan/iblis figürü çoğu zaman sınav, vesvese veya üstesinden gelinen bir tehdit motifi taşır; figürün akıbeti (uzaklaşması, defedilmesi) yorumda belirleyicidir.',
    jungHint: 'Shadow',
  },
  {
    id: 'road',
    name: 'yol',
    aliases: ['yol', 'yolda', 'patika', 'cadde'],
    themes: ['yön', 'hayat rotası', 'seçim'],
    psychological: 'Hayattaki mevcut rota, ilerleyiş hissi veya bir seçim noktası.',
    classical: 'Yol klasik olarak çoğu zaman yolculuk, kader çizgisi veya sınav süreci motifi taşır.',
    jungHint: null,
  },
]);

const BY_ID = new Map(DREAM_SYMBOL_CORPUS.map((s) => [s.id, s]));

/**
 * @param {string} id
 * @returns {DreamSymbol|null}
 */
export function getSymbolById(id) {
  return BY_ID.get(String(id)) || null;
}

/**
 * @returns {DreamSymbol[]}
 */
export function listSymbols() {
  return [...DREAM_SYMBOL_CORPUS];
}
